# Generated by Django 3.2.3 on 2021-05-22 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='property.basemodel')),
                ('status', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('fetched_from', models.CharField(max_length=200)),
            ],
            bases=('property.basemodel',),
        ),
    ]
